config/routes.rb
Rails.application.routes.draw do
  # Devise routes for users and admins
  devise_for :users, path: "users", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  devise_for :admins, path: "admins", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    invitations: "admins/invitations"
  }

  
  # Admin Routes
  devise_scope :admin do
    authenticated :admin do
      # API Routes
      namespace :api do 
        namespace :v1 do
          namespace :admins do
            resources :recipes, only: [] do
              collection do
                get :new_title
                post :create_title
                get :edit_title
              end

              member do
                patch :update_title
                patch :create_ingredient
                get :new_ingredient
                patch :edit_ingredient
                get :delete_ingredient
                patch :create_directions
                get :edit_direction
                patch :update_direction
                patch :delete_direction
              end
            end
          end
        end
      end

      get "dashboard", to: "admins/dashboard#index", as: :authenticated_root
      namespace :admins do
        # Dashboard and admin management
        resources :admins, except: [:create, :new]
        
        # Resources management
        resources :ingredient_states
        resources :measurement_units
        resources :groceries
        resources :grocery_categories
        resources :ingredients

        # Recipes management
        resources :recipes
      end
    end
  end

  # User Routes
  devise_scope :user do
    authenticated :user do
      # API Routes
      namespace :api do
        resources :lazyloads, only: [:index], controller: "lazy_loads"
        resources :mealplans, only: [:update, :show, :index], controller: "meal_plans"

        
        resources :plans, only: [] do
          collection do
            patch :meal_update, to: "v1/users/plans#meal_update"
            get :meal_plans_content, to: "v1/users/plans#meal_plans_content"
          end
        end
      end

      # User-specific routes
      namespace :users do
        get "plans", to: "plans#index", as: :authenticated_root
      end

      scope module: :users do
        resources :meal_plans

        resources :plans do
          collection do
            get "meal-plans"
            get "meal-plans-content"
            get "lazy-update"
            patch :meal_update
          end
          
          get "recipes/:id/meal_plan/:meal_plan_id", to: "recipes#show", as: "recipe", on: :collection
        end

        resources :groceries, only: [:index, :show], controller: "grocery_list"
        resources :recipes, only: [:show, :index, :single] do
          resources :favorites, only: [:create, :destroy]
          resources :reviews, only: [:create, :update] do
            member do
              patch "new"
              post "new"
            end

            collection do
              post "reply"
              patch "reply"
              patch "update_rating"
            end
          end
        end

        get "grocery-list", to: "grocery_list#show"
      end
    end

    # Additional user routes
    scope module: :users do
      get "recipes/single/:id", to: "recipes#single", as: :single_recipes
      get "recipes/single_post/:id", to: "recipes#single_post", as: :single_post_recipes
      resources :profiles, only: [:update, :edit, :show]
    end
  end

  # Additional Routes
  get "test", to: "home#testmailer"

  # Root path
  root "home#index"
end

app/models/measurement_unit.rb
class MeasurementUnit < ApplicationRecord
    has_many :ingredients, dependent: :destroy
end

app/controllers/admins/measurement_units_controller.rb
class Admins::MeasurementUnitsController < DashboardsController
  before_action :set_measurement_unit, only: %i[show edit update destroy]

  # GET /measurement_units or /measurement_units.json
  def index
    @pagy, @measurement_units = pagy(MeasurementUnit.limit(5))
  end

  # GET /measurement_units/1 or /measurement_units/1.json
  def show
  end

  # GET /measurement_units/new
  def new
    @measurement_unit = MeasurementUnit.new
  end

  # GET /measurement_units/1/edit
  def edit
  end

  # POST /measurement_units or /measurement_units.json
  def create
    @measurement_unit = MeasurementUnit.new(measurement_unit_params)

    respond_to do |format|
      if @measurement_unit.save
        format.html { redirect_to measurement_unit_url(@measurement_unit), notice: "Measurement unit was successfully created." }
        format.json { render :show, status: :created, location: @measurement_unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @measurement_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurement_units/1 or /measurement_units/1.json
  def update
    respond_to do |format|
      if @measurement_unit.update(measurement_unit_params)
        format.html { redirect_to measurement_unit_url(@measurement_unit), notice: "Measurement unit was successfully updated." }
        format.json { render :show, status: :ok, location: @measurement_unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @measurement_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurement_units/1 or /measurement_units/1.json
  def destroy
    @measurement_unit.destroy

    respond_to do |format|
      format.html { redirect_to measurement_units_url, notice: "Measurement unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_measurement_unit
    @measurement_unit = MeasurementUnit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def measurement_unit_params
    params.require(:measurement_unit).permit(:name, :description, :status)
  end
end

app/views/admins/measurement_units/_form.html.erb
<%= form_with(model: measurement_unit) do |form| %>
  <% if measurement_unit.errors.any? %>
    <div class="w-full">
      <h2><%= pluralize(measurement_unit.errors.count, "error") %> prohibited this measurement_unit from being saved:</h2>
      <ul>
        <% measurement_unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-full flex flex-col gap-4">
    <div class="w-full">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: "w-full" %>
    </div>
    <div class="w-full">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class: "w-full" %>
    </div>
    <div class="flex justify-end">
      <%= form.submit "Submit", class: "button button--primary" %>
    </div>
  </div>
<% end %>

app/views/admins/measurement_units/_measurement_unit.html.erb
<tr id="<%= dom_id measurement_unit %>"
>
  <td class="h-px w-px whitespace-nowrap">
    <div class="pl-6 py-3">
      <label for="hs-at-with-checkboxes-1" class="flex">
        <input type="checkbox" class="shrink-0 border-gray-200 rounded text-blue-600 pointer-events-none focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:checked:bg-blue-500 dark:checked:border-blue-500 dark:focus:ring-offset-gray-800" id="hs-at-with-checkboxes-1">
        <span class="sr-only">Checkbox</span>
      </label>
    </div>
  </td>
  <td class="h-px w-px whitespace-nowrap">
    <div class=" pr-6 py-3">
      <%#= link_to measurement_unit do %>
        <span class="block text-sm font-semibold text-gray-800 dark:text-gray-200"><%= measurement_unit.name %>
        </span>
        <%# end %>
      </div>
    </td>
    <td class="h-px w-px whitespace-nowrap">
      <div class="px-6 py-3">
        <span class="inline-flex items-center gap-1.5 py-0.5 px-2 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200">
          <svg class="w-2.5 h-2.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
          </svg>
          Active
        </span>
      </div>
    </td>
    <td class="h-px w-px whitespace-nowrap">
      <div class="px-6 py-3">
        <span class="text-sm text-gray-500"><%= measurement_unit[:created_at].to_date %></span>
      </div>
    </td>
    <td class="h-px w-px whitespace-nowrap ">
      <div class="flex justify-end gap-2 px-6 py-1.5">
        <%= button_to  edit_measurement_unit_path(measurement_unit), method: :get,  data: {turbo_frame: 'modal'}, class: "inline-flex items-center rounded-full px-2 py-1 text-white button--primary" do  %>
          <i class="bi bi-pencil"></i>
        <% end %>
        <%= button_to measurement_unit_path(measurement_unit.id), method: :delete, class: "inline-flex items-center gap-x-1.5 text-sm rounded-full text-white px-2 py-1 button--danger" do %>
          <i class="bi bi-trash"></i>
        <% end %>
        <%#= link_to "Back to recipes", recipes_path %>
      </div>
    </td>
  </tr>

app/views/admins/measurement_units/edit.html.erb
<%= render TurboModalComponent.new(title: "Editing measurement unit") do %>
  <%= render "form", measurement_unit: @measurement_unit %>
  <br>
  <div>
    <%= link_to "Show this measurement unit", @measurement_unit %> |
    <%= link_to "Back to measurement units", measurement_units_path %>
  </div>
<% end %>

app/views/admins/measurement_units/index.html.erb
<div class="page-container">
  <!------------------->
  <div id="recipes">
    <!-- Table Section -->
    <div class="max-w-[85rem] py-4 mx-auto">
      <h1 class="py-2 px-4 border-l-4 border-accent/70 text-primary text-3xl mb-4">Measurement units</h1>
      <!-- Card -->
      <div class="flex flex-col">
        <div class="-m-1.5 overflow-x-auto">
          <div class="p-1.5 min-w-full inline-block align-middle">
            <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden dark:bg-slate-900 dark:border-gray-700">
              <!-- Header -->
              <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200 dark:border-gray-700">
                <div>
                  <%# <h2 class="text-xl font-semibold text-gray-800 dark:text-gray-200">
                    Measurement units
                  </h2> %>
                  <p class="text-sm text-gray-600 dark:text-gray-400">
                    Add recipes, edit and more.
                  </p>
                </div>
                <div>
                  <div class="inline-flex gap-x-2">
                    <%= button_to  new_measurement_unit_path, method: :get, data: {turbo_frame: "modal"}, class: "flex gap-2 button button--secondary" do %>
                      <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                        <path d="M2.63452 7.50001L13.6345 7.5M8.13452 13V2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                      </svg>
                      Add
                    <% end %>
                  </div>
                </div>
              </div>
              <!-- End Header -->
              <!-- Table -->
              <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead class="bg-gray-50 dark:bg-slate-800">
                  <tr>
                    <th scope="col" class="pl-6 py-3 text-left">
                      <label for="hs-at-with-checkboxes-main" class="flex">
                        <input type="checkbox" class="shrink-0 border-gray-200 rounded text-blue-600 pointer-events-none focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700 dark:checked:bg-blue-500 dark:checked:border-blue-500 dark:focus:ring-offset-gray-800" id="hs-at-with-checkboxes-main">
                        <span class="sr-only">Checkbox</span>
                      </label>
                    </th>
                    <th scope="col" class="pl-6 lg:pl-3 xl:pl-0 pr-6 py-3 text-left">
                      <div class="flex items-center gap-x-2">
                        <span class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-gray-200">
                          Name
                        </span>
                      </div>
                    </th>
                    <th scope="col" class="px-6 py-3 text-left">
                      <div class="flex items-center gap-x-2">
                        <span class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-gray-200">
                          Status
                        </span>
                      </div>
                    </th>
                    <th scope="col" class="px-6 py-3 text-left">
                      <div class="flex items-center gap-x-2">
                        <span class="text-xs font-semibold uppercase tracking-wide text-gray-800 dark:text-gray-200">
                          Created
                        </span>
                      </div>
                    </th>
                    <th scope="col" class="px-6 py-3 text-right"></th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
                  <% @measurement_units.each do |measurement_unit| %>
                    <%= render measurement_unit %>
                  <% end %>
                </tbody>
              </table>
              <!-- End Table -->
              <!-- Footer -->
              <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-t border-gray-200 dark:border-gray-700">
                <div>
                  <p class="text-sm text-gray-600 dark:text-gray-400">
                    <span class="font-semibold text-gray-800 dark:text-gray-200"><%= pluralize(@measurement_units.count, 'result')  %></span>
                  </p>
                </div>
                <div>
                  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
                </div>
              </div>
              <!-- End Footer -->
            </div>
          </div>
        </div>
      </div>
      <!-- End Card -->
    </div>
    <!-- End Table Section -->
  </div>
  <!------------------->
</div>

app/views/admins/measurement_units/new.html.erb
<%= render TurboModalComponent.new(title: "New measurement unit") do %>
  <%= render "form", measurement_unit: @measurement_unit %>
  <br>
  <div>
    <%= link_to "Back to measurement units", measurement_units_path %>
  </div>
<% end %>

app/views/admins/measurement_units/show.html.erb
<div class="max-w-5xl mx-auto h-full py-16">
  <p style="color: green"><%= notice %></p>
  <%=  @measurement_unit.name %>
  <div class="flex justify-end gap-4">
    <%= link_to "Edit this measurement unit", edit_measurement_unit_path(@measurement_unit) %> |
    <%= link_to "Back to measurement units", measurement_units_path %>
    <%= button_to "Destroy this measurement unit", @measurement_unit, method: :delete %>
  </div>
</div>