config/routes.rb
Rails.application.routes.draw do
  # Devise routes for users and admins
  devise_for :users, path: "users", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  devise_for :admins, path: "admins", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    invitations: "admins/invitations"
  }

  
  # Admin Routes
  devise_scope :admin do
    authenticated :admin do
      # API Routes
      namespace :api do 
        namespace :v1 do
          namespace :admins do
            resources :recipes, only: [] do
              collection do
                get :new_title
                post :create_title
                get :edit_title
              end

              member do
                patch :update_title
                patch :create_ingredient
                get :new_ingredient
                patch :edit_ingredient
                get :delete_ingredient
                patch :create_directions
                get :edit_direction
                patch :update_direction
                patch :delete_direction
              end
            end
          end
        end
      end

      get "dashboard", to: "admins/dashboard#index", as: :authenticated_root
      namespace :admins do
        # Dashboard and admin management
        resources :admins, except: [:create, :new]
        
        # Resources management
        resources :ingredient_states
        resources :measurement_units
        resources :groceries
        resources :grocery_categories
        resources :ingredients

        # Recipes management
        resources :recipes
      end
    end
  end

  # User Routes
  devise_scope :user do
    authenticated :user do
      # API Routes
      namespace :api do
        resources :lazyloads, only: [:index], controller: "lazy_loads"
        resources :mealplans, only: [:update, :show, :index], controller: "meal_plans"

        
        resources :plans, only: [] do
          collection do
            patch :meal_update, to: "v1/users/plans#meal_update"
            get :meal_plans_content, to: "v1/users/plans#meal_plans_content"
          end
        end
      end

      # User-specific routes
      namespace :users do
        get "plans", to: "plans#index", as: :authenticated_root
      end

      scope module: :users do
        resources :meal_plans

        resources :plans do
          collection do
            get "meal-plans"
            get "meal-plans-content"
            get "lazy-update"
            patch :meal_update
          end
          
          get "recipes/:id/meal_plan/:meal_plan_id", to: "recipes#show", as: "recipe", on: :collection
        end

        resources :groceries, only: [:index, :show], controller: "grocery_list"
        resources :recipes, only: [:show, :index, :single] do
          resources :favorites, only: [:create, :destroy]
          resources :reviews, only: [:create, :update] do
            member do
              patch "new"
              post "new"
            end

            collection do
              post "reply"
              patch "reply"
              patch "update_rating"
            end
          end
        end

        get "grocery-list", to: "grocery_list#show"
      end
    end

    # Additional user routes
    scope module: :users do
      get "recipes/single/:id", to: "recipes#single", as: :single_recipes
      get "recipes/single_post/:id", to: "recipes#single_post", as: :single_post_recipes
      resources :profiles, only: [:update, :edit, :show]
    end
  end

  # Additional Routes
  get "test", to: "home#testmailer"

  # Root path
  root "home#index"
end

app/views/shared/_navbar.html.erb
<% bg = controller.controller_name == "home" ? "bg-white" : "bg-primary" %>
<header class="sticky top-0 inset-x-0 flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full <%= bg %> text-gray-800 text-sm py-3 sm:py-0">
  <nav class="relative max-w-[85rem] w-full mx-auto px-4 py-2 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8" aria-label="Global">
    <div class="flex items-center justify-between">
      <a class="flex-none text-xl font-semibold" href="/" aria-label="Brand">
        <%= image_tag "logo.png", width: 100 %>
      </a>
      <div class="sm:hidden">
        <button type="button" class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-2 rounded-md border font-medium <%= controller.controller_name == "home" ? "text-black/[.5] border-black/[.5]" : "text-white border-black/[.5]" %>  shadow-sm align-middle hover:bg-white/[.1] hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm" data-hs-collapse="#navbar-collapse-with-animation" aria-controls="navbar-collapse-with-animation" aria-label="Toggle navigation">
          <svg class="hs-collapse-open:hidden w-4 h-4" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
          <svg class="hs-collapse-open:block hidden w-4 h-4" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
        </button>
      </div>
    </div>
    <div id="navbar-collapse-with-animation" class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
      <div class="flex flex-col gap-y-4 gap-x-0 mt-5 sm:flex-row sm:items-center sm:justify-end sm:gap-y-0 sm:gap-x-7 sm:mt-0 sm:pl-7">
        <% if user_signed_in? || admin_signed_in? %>
          <a href="#" class="#">About</a>
          <% if admin_signed_in? %>
            <%= link_to "Dashboard",  authenticated_root_path, class: "font-medium sm:py-1 px-1" %>
            <%= link_to "Users",  admins_admins_path, class: "font-medium sm:py-1 px-1" %>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to "Plan", plans_url, class: "font-medium sm:py-1 px-1" %>
          <% end %>
          <div class="flex items-center gap-2 avatar">
            <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none] sm:[--trigger:hover] sm:py-1">
              <button type="button" class="flex items-center w-full  font-medium">
                <% if user_signed_in? %>
                  <%= profile_image %>
                <% end %>
                <% if admin_signed_in? %>
                  <%= current_admin&.email ? current_admin&.email : current_user&.email %>
                  <svg class="ml-2 w-2.5 h-2.5" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 5L8.16086 10.6869C8.35239 10.8637 8.64761 10.8637 8.83914 10.6869L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round"></path>
                  </svg>
                <% end %>
              </button>
              <div class="hs-dropdown-menu transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 hidden z-10 bg-white sm:shadow-md rounded-lg p-2 before:absolute top-full sm:border before:-top-5 before:left-0 before:w-full before:h-5">
                <div class="flex flex-col">
                  <% if user_signed_in? %>
                    <%= link_to "Profile", edit_profile_path(current_user), class: "p-2 w-full hover:bg-gray-300 rounded-md" %>
                    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "w-full flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300  group-hover:bg-gray-300" %>
                  <% elsif !admin_signed_in? %>
                    <%= link_to "Sign In", new_user_session_path %>
                  <% end %>
                  <% if admin_signed_in? %>
                    <%= button_to 'Sign Out as Admin', destroy_admin_session_path, method: :delete %>
                  <% elsif !user_signed_in? %>
                    <%= link_to "Sign In as Admin", new_admin_session_path %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "font-medium  hover:text-gray-400 px-4 py-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "font-medium text-white/[.8] hover:text-white button button--primary" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_navbar_admin.html.erb
<% bg = controller.controller_name == "home" ? "bg-white" : "bg-primary" %>
<header class="sticky top-0 inset-x-0 flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full <%= bg %> text-gray-800 text-sm py-3 sm:py-0">
  <nav class="relative max-w-[85rem] w-full mx-auto px-4 py-2 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8" aria-label="Global">
    <div class="flex items-center justify-between">
      <a class="flex-none text-xl font-semibold" href="/" aria-label="Brand">
        <%= image_tag "logo.png", width: 100 %>
      </a>
      <div class="sm:hidden">
        <button type="button" class="hs-collapse-toggle p-2 inline-flex justify-center items-center gap-2 rounded-md border font-medium <%= controller.controller_name == "home" ? "text-black/[.5] border-black/[.5]" : "text-white border-black/[.5]" %>  shadow-sm align-middle hover:bg-white/[.1] hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm" data-hs-collapse="#navbar-collapse-with-animation" aria-controls="navbar-collapse-with-animation" aria-label="Toggle navigation">
          <svg class="hs-collapse-open:hidden w-4 h-4" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
          <svg class="hs-collapse-open:block hidden w-4 h-4" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
          </svg>
        </button>
      </div>
    </div>
    <div id="navbar-collapse-with-animation" class="hs-collapse hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
      <div class="flex flex-col gap-y-4 gap-x-0 mt-5 sm:flex-row sm:items-center sm:justify-end sm:gap-y-0 sm:gap-x-7 sm:mt-0 sm:pl-7">
        <% if user_signed_in? || admin_signed_in? %>
          <a href="#" class="#">About</a>
          <% if admin_signed_in? %>
            <%= link_to "Dashboard",  authenticated_root_path, class: "font-medium sm:py-1 px-1" %>
            <%= link_to "Users",  admins_admins_path, class: "font-medium sm:py-1 px-1" %>
          <% end %>
          <% if user_signed_in? %>
            <%= link_to "Plan", plans_url, class: "font-medium sm:py-1 px-1" %>
          <% end %>
          <div class="flex items-center gap-2 avatar">
            <div class="hs-dropdown [--strategy:static] sm:[--strategy:fixed] [--adaptive:none] sm:[--trigger:hover] sm:py-1">
              <button type="button" class="flex items-center w-full  font-medium">
                <% if user_signed_in? %>
                  <%= profile_image %>
                <% end %>
                <% if admin_signed_in? %>
                  <%= current_admin&.email ? current_admin&.email : current_user&.email %>
                  <svg class="ml-2 w-2.5 h-2.5" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2 5L8.16086 10.6869C8.35239 10.8637 8.64761 10.8637 8.83914 10.6869L15 5" stroke="currentColor" stroke-width="2" stroke-linecap="round"></path>
                  </svg>
                <% end %>
              </button>
              <div class="hs-dropdown-menu transition-[opacity,margin] duration-[0.1ms] sm:duration-[150ms] hs-dropdown-open:opacity-100 opacity-0 sm:w-48 hidden z-10 bg-white sm:shadow-md rounded-lg p-2 before:absolute top-full sm:border before:-top-5 before:left-0 before:w-full before:h-5">
                <div class="flex flex-col">
                  <% if user_signed_in? %>
                    <%= link_to "Profile", edit_profile_path(current_user), class: "p-2 w-full hover:bg-gray-300 rounded-md" %>
                    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "w-full flex items-center gap-x-3.5 py-2 px-3 rounded-md text-sm text-gray-800 hover:bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300  group-hover:bg-gray-300" %>
                  <% elsif !admin_signed_in? %>
                    <%= link_to "Sign In", new_user_session_path %>
                  <% end %>
                  <% if admin_signed_in? %>
                    <%= button_to 'Sign Out as Admin', destroy_admin_session_path, method: :delete %>
                  <% elsif !user_signed_in? %>
                    <%= link_to "Sign In as Admin", new_admin_session_path %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "font-medium  hover:text-gray-400 px-4 py-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "font-medium text-white/[.8] hover:text-white button button--primary" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>
<div class="w-full fixed top-14 z-50">
  <%= render "application/flash" %>
</div>

app/views/shared/_spinner_bubble.html.erb
<div class="border border-accent/50 rounded-md loading-indicator hidden absolute top-0 left-0 right-0 bottom-0 h-full w-full z-10 backdrop-filter backdrop-blur-md bg-white/80" data-navigation-target="loading">
  <div class="flex items-center justify-center h-full w-full">
    <span class="loader"></span>
  </div>
</div>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="flex gap-0.5 back-stars">
    <% (1..5).map do |n| %>
      <%= button_to update_rating_recipe_reviews_path(recipe), 
          method: :patch, 
          params: { review: { rating: n, id: review.id, recipe_id: recipe.id } }, 
          class: "p-0 m-0 " do %>
        <% unless review.stars == nil %>
          <%= inline_svg_tag(
          "svg/star.svg", 
          size: '30% * 20%', 
          class: "w-4 h-4 hover:fill-yellow-500 hover:stroke-yellow-500 #{star_rating_class(review, n)}"
        ) %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_turbo_frame_wrap.html.erb
<% if name.present? %><turbo-frame id="<%= name %>"><% end %>
  <%= yield %>
  <% if name.present? %></turbo-frame><% end %>