config/routes.rb
Rails.application.routes.draw do
  # Devise routes for users and admins
  devise_for :users, path: "users", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  devise_for :admins, path: "admins", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    invitations: "admins/invitations"
  }

  
  # Admin Routes
  devise_scope :admin do
    authenticated :admin do
      # API Routes
      namespace :api do 
        namespace :v1 do
          namespace :admins do
            resources :recipes, only: [] do
              collection do
                get :new_title
                post :create_title
                get :edit_title
              end

              member do
                patch :update_title
                patch :create_ingredient
                get :new_ingredient
                patch :edit_ingredient
                get :delete_ingredient
                patch :create_directions
                get :edit_direction
                patch :update_direction
                patch :delete_direction
              end
            end
          end
        end
      end

      get "dashboard", to: "admins/dashboard#index", as: :authenticated_root
      namespace :admins do
        # Dashboard and admin management
        resources :admins, except: [:create, :new]
        
        # Resources management
        resources :ingredient_states
        resources :measurement_units
        resources :groceries
        resources :grocery_categories
        resources :ingredients

        # Recipes management
        resources :recipes
      end
    end
  end

  # User Routes
  devise_scope :user do
    authenticated :user do
      # API Routes
      namespace :api do
        resources :lazyloads, only: [:index], controller: "lazy_loads"
        resources :mealplans, only: [:update, :show, :index], controller: "meal_plans"

        
        resources :plans, only: [] do
          collection do
            patch :meal_update, to: "v1/users/plans#meal_update"
            get :meal_plans_content, to: "v1/users/plans#meal_plans_content"
          end
        end
      end

      # User-specific routes
      namespace :users do
        get "plans", to: "plans#index", as: :authenticated_root
      end

      scope module: :users do
        resources :meal_plans

        resources :plans do
          collection do
            get "meal-plans"
            get "meal-plans-content"
            get "lazy-update"
            patch :meal_update
          end
          
          get "recipes/:id/meal_plan/:meal_plan_id", to: "recipes#show", as: "recipe", on: :collection
        end

        resources :groceries, only: [:index, :show], controller: "grocery_list"
        resources :recipes, only: [:show, :index, :single] do
          resources :favorites, only: [:create, :destroy]
          resources :reviews, only: [:create, :update] do
            member do
              patch "new"
              post "new"
            end

            collection do
              post "reply"
              patch "reply"
              patch "update_rating"
            end
          end
        end

        get "grocery-list", to: "grocery_list#show"
      end
    end

    # Additional user routes
    scope module: :users do
      get "recipes/single/:id", to: "recipes#single", as: :single_recipes
      get "recipes/single_post/:id", to: "recipes#single_post", as: :single_post_recipes
      resources :profiles, only: [:update, :edit, :show]
    end
  end

  # Additional Routes
  get "test", to: "home#testmailer"

  # Root path
  root "home#index"
end

app/controllers/admins/ingredients_controller.rb
class Admins::IngredientsController < DashboardsController 
  before_action :set_ingredient, only: %i[ edit show update destroy create ]
  # before_action :set_recipe, excerpt: %i[ updated ]

  def index
    @recipes = Ingredient.all.includes(:grocery, :measurement_unit, :ingredient_state)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = @recipe.ingredients.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        flash.now[:notice] = "Ingredient created successfully"

        format.turbo_stream
      end
    end
  end

  def edit
  end

  def show
  end

  def update
   
    @recipe = Recipe.find(params[:recipe_id])

    respond_to do |format|
      # p @meal_plan
      
      if @ingredient.update!(ingredient_params)
        # p "ingredient--#{@ingredient}"
        
        # Turbo::StreamsChannel.broadcast_replace_to :mealplans_list, target: @plan
          # Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, 
          #   target: "ingredient--ingredient_#{@ingredient.id}", 
          #   partial: "admins/recipes/ingredient/recipe_sub_ingredient_list", 
          #   locals: {id: @recipe.id, index: 0, ingredient: @ingredient, recipe: @recipe}

        flash.now[:notice] = "Ingredient updated successfully"

        format.turbo_stream
        format.html { }
        format.json { render :json, status: :ok, location: @ingredient }
      else
        # format.turbo_stream
        # format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    @ingredient.destroy

    respond_to do |format|
      
      flash.now[:alert] = "Ingredient deleted successfully"

      format.turbo_stream
      format.html { }
      format.json { head :no_content }
    end
  end


 


private
  # Use callbacks to share common setup or constraints between actions.
  def set_ingredient
    p "----------------------------------------------"
    p params
    p @ingredient
    p "----------------------------------------------"
    if params[:id].present?
      @ingredient = Ingredient.find(params[:id].to_i)
    end

    if params[:recipe_id].present?
      @recipe = Recipe.find(params[:recipe_id].to_i)
    end
  end


  def ingredient_params
      params.permit(:quantity, :measurement_unit_id, :ingredient_state_id, :grocery_id, :recipe_id)
  end
end

app/controllers/admins/recipes_controller.rb
class Admins::RecipesController < DashboardsController 
  # before_action :ensure_frame_response, only: [:new, :create, :title]
  before_action :set_recipe, only: %i[ show edit edit_title update_title create_directions update destroy ]


  # GET /recipes or /recipes.json
  def index
    @pagy, @recipes = pagy(Recipe.includes(:recipe_category).order(created_at: :DESC))
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_ingredients = Ingredient.includes(:grocery, :measurement_unit, :ingredient_state).where(recipe_id: @recipe.id).order("id ASC")
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe_ingredients = Ingredient.includes(:grocery, :measurement_unit, :ingredient_state).where(recipe_id: @recipe.id).order("id ASC")
          
    # Turbo::StreamsChannel.broadcast_append_to :recipe_form_update, 
    #   target: "recipe-ingredients--list", 
    #   partial: "recipes/recipe_sub_ingredient", 
    #   locals: {id: @recipe.id, recipe_ingredient: @recipe_ingredients, recipe: @recipe}
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.turbo_stream
        format.html { redirect_to admins_recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.turbo_stream
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # def create_ingredient
  #   @recipe = Recipe.find(params[:id])
  #   @recipe_ingredient = @recipe.ingredients.new(quantity: recipe_ingredient_params[:quantity], grocery_id: recipe_ingredient_params[:grocery_id], measurement_unit_id: recipe_ingredient_params[:measurement_unit_id], ingredient_state_id: recipe_ingredient_params[:ingredient_state_id])
    
  #   respond_to do |format|
  #     if @recipe_ingredient.save
  #       # Turbo::StreamsChannel.broadcast_prepend_to :recipe_form_update, 
  #         #   target: "recipe_#{@recipe.id}", 
  #         #   partial: "admins/recipes/ingredient/recipe_sub_ingredient_list", 
  #         #   locals: {
  #           #     recipe_id: @recipe.id, 
  #         #     index: 0, 
  #         #     ingredient: @recipe_ingredient, 
  #         #     recipe: @recipe
  #         #   }

          
  #         flash.now[:notice] = "Recipe was successfully updated." 
  #         flash.now[:alert] = "Recipe was successfully updated." 
  #         # render turbo_stream: [
  #         #       turbo_stream.prepend(
  #         #         "recipe_#{@recipe.id}",
  #         #         partial: "admins/recipes/ingredient/recipe_sub_ingredient_list",
  #         #         locals: {
  #         #           recipe_id: @recipe.id, 
  #         #           index: 0, 
  #         #           ingredient: @recipe_ingredient, 
  #         #           recipe: @recipe
  #         #         },
  #         #       ),
  #         #       turbo_stream.replace("flash", partial: "application/flash"),
  #         #     ]

  #       format.turbo_stream
  #       format.html {  }
  #       format.js
  #       format.json { render json: {status: :ok } }    
  #     else  
  #       flash.now[:notice] = @recipe_ingredient.errors
  #       Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, 
  #           target: "recipe_ingredient_form", 
  #           partial: "admins/recipes/ingredient/recipe_sub_ingredient_form", 
  #           locals: {
  #             ingredient: @recipe_ingredient, 
  #             recipe_id: @recipe.id
  #           }


  #       # format.html { render :edit, status: :unprocessable_entity }
  #       # format.json { render json: @recipe_ingredient.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end



  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
   
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to edit_admins_recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to admins_recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # DIRECTIONS -------------------------------------
  
  # DIRECTIONS -------------------------------------

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :image, :recipe_category_id, :status)
    end

    def recipe_ingredient_params
      params.permit(:quantity, :ingredient_state_id, :measurement_unit_id, :grocery_id)
    end

    # def ensure_frame_response
    #   return unless Rails.env.development?
    #   redirect_to recipes_url unless turbo_frame_request?
    # end
end

app/controllers/api/v1/admins/recipe_controller.rb
module Api
  module V1
    module Admins
      class RecipeController < DashboardsController
        before_action :set_recipe, only: %i[  edit_title update_title create_directions ]

        def new_title
          @recipe = Recipe.new
        end

        def create_title
          if params[:edit]
            @recipe = Recipe.find(params[:id])
            @recipe.title = params[:title]
          else
            @recipe = Recipe.new(recipe_params)
          end


          respond_to do |format| 
            if @recipe.save
              # format.turbo_stream {render turbo_stream: turbo_stream.replace(@recipe)}
              # format.turbo_stream
              # format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
              # Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, target: "recipe-update-#{@recipe.id}", partial: "recipes/recipe_sub_form", locals: {id: @recipe.id}
              format.json { render :show, status: :created, location: @recipe }
            else
              format.html { render :new_title, status: :unprocessable_entity }
              format.json { render json: @recipe.errors, status: :unprocessable_entity }
            end
          end
        end

        def edit_title
        end

        def update_title
          respond_to do |format| 
            if @recipe.update(recipe_params)
              # format.turbo_stream {render turbo_stream: turbo_stream.replace(@recipe)}
              # format.turbo_stream
              # format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
              # Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, target: "recipe-update-#{@recipe.id}", partial: "recipes/recipe_sub_form", locals: {id: @recipe.id}
              format.json { render :index, status: :created, location: @recipe }
            else
              format.html { render :new_title, status: :unprocessable_entity }
              format.json { render json: @recipe.errors, status: :unprocessable_entity }
            end
          end
        end

        def new_ingredient
          @ingredient = Ingredient.new
          @recipe_id = params[:id]
        end

        def edit_ingredient
        end

        def create_directions
          params[:direction].each do |index, item|
            @recipe.directions << item
          end

          if @recipe.save
            Turbo::StreamsChannel.broadcast_prepend_to :recipe_form_update, 
                  target: "recipe_#{@recipe.id}", 
                  partial: "admins/recipes/recipe_sub_ingredient_list", 
                  locals: {id: @recipe.id, index: 0, ingredient: @recipe_ingredient, recipe: @recipe}

            flash.now[:notice] = "Recipe direction created successfully"

            format.turbo_stream
            format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
            format.json { render :show, status: :ok, location: @recipe }
          else 
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end
        end

        def edit_direction
          direction_id = params[:direction_id].to_i
          @direction_id = direction_id || 2
          # @ingredient = Recipe.find(params[:recipe_id]).directions.select.with_index{ |direction, index| index === direction_id}
          ingredient = Recipe.find(params[:recipe_id]).directions
          @ingredient = ingredient.select.with_index{|ingredient, idx|  idx === direction_id}
          @recipe_id = params[:recipe_id]
        end

        def update_direction
          ingredient = Recipe.find(params[:recipe_id])
          ingredient.directions[params[:id].to_i] = params[:direction]

          if  ingredient.save!
            # Turbo::StreamsChannel.broadcast_prepend_to :recipe_form_update, 
            #       target: "recipe_#{@recipe.id}", 
            #       partial: "recipes/recipe_sub_ingredient_list", 
            #       locals: {id: @recipe.id, index: 0, ingredient: @recipe_ingredient, recipe: @recipe}
            flash.now[:notice] = "Recipe direction updated successfully"

            format.turbo_stream

            format.html {  }
            format.json {  }
          else 
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end
        end


        def delete_direction
          ingredient = Recipe.find(params[:recipe_id])
          ingredient.directions.delete_at(params[:id])

          if  ingredient.save!
            Turbo::StreamsChannel.broadcast_remove_to :recipe_form_update, target: "edit_ddirection_#{params[:id]}"

            flash.now[:alert] = "Recipe direction deleted successfully"
            format.html {  }
            format.json {  }
          else 
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end
        end


        private

        def set_recipe
          @recipe = Recipe.find(params[:id])
        end

      end
    end
  end
end

app/helpers/users/recipes_helper.rb
module Users::RecipesHelper
    def average_stars(recipe)
        if recipe.average_stars.zero?
            content_tag(:strong, "No reviews")
        else
            pluralize(number_with_precision(recipe.average_stars, precision: 1), "star")
        end
    end
end

app/views/admins/recipes/ingredient/__recipe_sub_ingredient_form.html.erb
<%# <turbo-frame id="recipe_ingredient_form"> %>
<%#= turbo_frame_tag "recipe_ingredient_form" do %>
  <div id="recipe_ingredient_form"  data-controller="recipe" data-recipe-id-value="<%= recipe_id %>" class="flex flex-col gap-4 max-w-2xl">
    <% if ingredient.errors.any? %>
      <div style="color: red">
        <h2><span class="py-1 px-2 bg-slate-400 rounded-full"><%= pluralize(ingredient.errors.count, "error") %></span> prohibited this Ingredient from being saved:</h2>
        <ul>
          <% ingredient.errors.each do |error| %>
            <li class="font-bold"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <form id="_recipe_ingredient_form" class="flex flex-col gap-4">
      <div class="flex flex-col">
        <label class="text-gray-500">Quantity</label>
        <input name="quantity" type="number" step=".1" value="<%= ingredient[:quantity] %>" placeholder="0.5" />
      </div>
      <div  class="w-full  flex flex-col">
        <label class="text-gray-500">Measurement Uni</label>
        <select value="<%= ingredient[:measurement_unit_id] %>" name="measurement_unit_id">
          <% MeasurementUnit.all.map do |result| %>
            <option value="<%= result.id %>" <%= "selected" if ingredient[:measurement_unit_id] == result.id %> ><%= result.name %></option>
          <% end %>
        </select>
      </div>
      <div class="w-full flex flex-col">
        <label class="text-gray-500">Ingredient State</label>
        <select value="<%= ingredient[:ingredient_state_id] %>" name="ingredient_state_id">
          <% IngredientState.all.map do |result| %>
            <option value="<%= result.id %>" <%= "selected" if ingredient[:ingredient_state_id] == result.id %> ><%= result.name %></option>
          <% end %>
        </select>
      </div>
      <div class="w-full  flex flex-col">
        <label class="text-gray-500">Grocery</label>
        <select value="<%= ingredient[:grocery_id] %>" name="grocery_id">
          <% Grocery.all.map do |result| %>
            <option value="<%= result.id %>"  <%= "selected" if ingredient[:grocery_id] == result.id %> ><%= result.name %></option>
          <% end %>
        </select>
      </div>
      <div class="flex justify-end mt-4">
        <%# <input type="hidden" name="authenticity_token" value="= form_authenticity_token"> %>
        <button class="button--primary rounded-md text-white p-2"   value="submit" data-action="click->recipe#create_ingredient">Add Ingredient</button>
      </div>
    </form>
  </div>
  <%# end %>
  <%# </turbo-frame> %>

app/views/admins/recipes/ingredient/_recipe_sub_ingredient.html.erb
<div class="flex flex-col gap-4  shadow-sm border border-gray-100 pt-2 px-4 pb-4 relative">
  <h3 class=" text-xl text-black font-bold">Ingredients</h3>
  <% if defined? edit%>
    <div class="flex flex-row justify-between absolute top-2 right-3">
      <%= link_to new_admins_ingredient_recipe_path, 
      method: :get,  data: {turbo_frame: "modal", "hs-overlay": "#hs-vertically-centered-modal"}, 
      class: "py-1 px-2 inline-flex justify-center items-center gap-2  rounded-md button--secondary text-gray-100" do  %>
        <i class="bi bi-plus-lg text-xl font-semibold"></i> Add
      <% end %>
    </div>
  <% end %>
  <div id="recipe-ingredients--list-<%= recipe.id %>">
    <ul id="recipe_<%= recipe.id %>" class="flex flex-col">
      <% recipe_ingredient.each_with_index do |ingredient, index| %>
        <%= render "admins/recipes/ingredient/recipe_sub_ingredient_list", ingredient: ingredient, index: index + 1 %>
      <% end %>
    </ul>
  </div>
  <%#= turbo_frame_tag "modal" %>
</div>

app/views/admins/recipes/ingredient/_recipe_sub_ingredient_form.html.erb
<%# <turbo-frame id="recipe_ingredient_form"> %>
<%#= turbo_frame_tag "recipe_ingredient_form" do %>
  <div id="recipe_ingredient_form"   class="flex flex-col gap-4 max-w-2xl">
    <% if ingredient.errors.any? %>
      <div style="color: red">
        <h2><span class="py-1 px-2 bg-slate-400 rounded-full"><%= pluralize(ingredient.errors.count, "error") %></span> prohibited this Ingredient from being saved:</h2>
        <ul>
          <% ingredient.errors.each do |error| %>
            <li class="font-bold"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with url: '/ingredients', method: :post, html: {id: "_recipe_ingredient_form", class: "flex flex-col gap-4"} do  %>
      <div class="flex flex-col">
        <label class="text-gray-500">Quantity</label>
        <input name="quantity" type="number" step=".1" value="<%= ingredient[:quantity] %>" placeholder="0.5" />
      </div>
      <div  class="w-full  flex flex-col">
        <label class="text-gray-500">Measurement Uni</label>
        <select value="<%= ingredient[:measurement_unit_id] %>" name="measurement_unit_id">
          <% MeasurementUnit.all.map do |result| %>
            <option value="<%= result.id %>" <%= "selected" if ingredient[:measurement_unit_id] == result.id %> ><%= result.name %></option>
          <% end %>
        </select>
      </div>
      <div class="w-full flex flex-col">
        <label class="text-gray-500">Ingredient State</label>
        <select value="<%= ingredient[:ingredient_state_id] %>" name="ingredient_state_id">
          <% IngredientState.all.map do |result| %>
            <option value="<%= result.id %>" <%= "selected" if ingredient[:ingredient_state_id] == result.id %> ><%= result.name %></option>
          <% end %>
        </select>
      </div>
      <div class="w-full  flex flex-col">
        <label class="text-gray-500">Grocery</label>
        <select value="<%= ingredient[:grocery_id] %>" name="grocery_id">
          <% Grocery.all.map do |result| %>
            <option value="<%= result.id %>"  <%= "selected" if ingredient[:grocery_id] == result.id %> ><%= result.name %></option>
          <% end %>
        </select>
      </div>
      <div class="flex justify-end mt-4">
        <input hidden value="<%= recipe_id %>" name="recipe_id">
        <%# <input type="hidden" name="authenticity_token" value="= form_authenticity_token"> %>
        <%= submit_tag 'save', class: "button button--primary" %>
      </div>
    <% end %>
  </div>
  <%# end %>
  <%# </turbo-frame> %>

app/views/admins/recipes/ingredient/_recipe_sub_ingredient_list.html.erb
<li id="ingredient--<%= dom_id(ingredient) %>" class="flex justify-between bg-gray-50 hover:bg-gray-200 gap-2 mb-1">
  <div class="flex gap-2">
    <span class="w-8 text-white font-extrabold px-3 bg-gray-200">
      <%= index %>
    </span>
    <span>
      <%= ingredient.quantity %> <%= ingredient.measurement_unit.name %>
      - <%= ingredient.grocery.name %> - <%= ingredient.ingredient_state.name %>
    </span>
  </div>
  <% #if admin_signed_in? %>
  <span class="flex items-center gap-1 py-1">
    <%= button_to  admins_ingredient_path(ingredient), 
      method: :get, 
      data: {turbo_frame: 'modal'}, class: "bg-gray-500 hover:bg-gray-700 text-gray-200 hover:text-white px-1 rounded-md" do %>
      <i class="bi bi-eye"></i>
    <% end %>
    <%= button_to  edit_admins_ingredient_path(ingredient), 
      method: :get, 
      params: {recipe_id: ingredient.recipe_id}, 
      data: {turbo_frame: 'modal'}, class: "bg-gray-300 hover:bg-gray-700 text-black hover:text-white px-1 rounded-md" do %>
      <i class="bi bi-pencil"></i>
    <% end %>
    <%= link_to admins_ingredient_path(ingredient), 
        data: { 'turbo-method': "delete", 'delete-target': "link", 
        action: "turbo:click->recipe#delete" },  
        class: "bg-gray-300 hover:bg-red-700 text-red-400 text-black hover:text-white px-1 rounded-md" do %>
      <i class="bi bi-trash"></i>
    <% end %>
  </span>
  <% #end %>
</li>