config/routes.rb
Rails.application.routes.draw do
  # Devise routes for users and admins
  devise_for :users, path: "users", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations"
  }

  devise_for :admins, path: "admins", controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    invitations: "admins/invitations"
  }

  
  # Admin Routes
  devise_scope :admin do
    authenticated :admin do
      # API Routes
      namespace :api do 
        namespace :v1 do
          namespace :admins do
            resources :recipes, only: [] do
              collection do
                get :new_title
                post :create_title
                get :edit_title
              end

              member do
                patch :update_title
                patch :create_ingredient
                get :new_ingredient
                patch :edit_ingredient
                get :delete_ingredient
                patch :create_directions
                get :edit_direction
                patch :update_direction
                patch :delete_direction
              end
            end
          end
        end
      end

      get "dashboard", to: "admins/dashboard#index", as: :authenticated_root
      namespace :admins do
        # Dashboard and admin management
        resources :admins, except: [:create, :new]
        
        # Resources management
        resources :ingredient_states
        resources :measurement_units
        resources :groceries
        resources :grocery_categories
        resources :ingredients

        # Recipes management
        resources :recipes
      end
    end
  end

  # User Routes
  devise_scope :user do
    authenticated :user do
      # API Routes
      namespace :api do
        resources :lazyloads, only: [:index], controller: "lazy_loads"
        resources :mealplans, only: [:update, :show, :index], controller: "meal_plans"

        
        resources :plans, only: [] do
          collection do
            patch :meal_update, to: "v1/users/plans#meal_update"
            get :meal_plans_content, to: "v1/users/plans#meal_plans_content"
          end
        end
      end

      # User-specific routes
      namespace :users do
        get "plans", to: "plans#index", as: :authenticated_root
      end

      scope module: :users do
        resources :meal_plans

        resources :plans do
          collection do
            get "meal-plans"
            get "meal-plans-content"
            get "lazy-update"
            patch :meal_update
          end
          
          get "recipes/:id/meal_plan/:meal_plan_id", to: "recipes#show", as: "recipe", on: :collection
        end

        resources :groceries, only: [:index, :show], controller: "grocery_list"
        resources :recipes, only: [:show, :index, :single] do
          resources :favorites, only: [:create, :destroy]
          resources :reviews, only: [:create, :update] do
            member do
              patch "new"
              post "new"
            end

            collection do
              post "reply"
              patch "reply"
              patch "update_rating"
            end
          end
        end

        get "grocery-list", to: "grocery_list#show"
      end
    end

    # Additional user routes
    scope module: :users do
      get "recipes/single/:id", to: "recipes#single", as: :single_recipes
      get "recipes/single_post/:id", to: "recipes#single_post", as: :single_post_recipes
      resources :profiles, only: [:update, :edit, :show]
    end
  end

  # Additional Routes
  get "test", to: "home#testmailer"

  # Root path
  root "home#index"
end

app/controllers/admins/recipes_controller.rb
class Admins::RecipesController < DashboardsController 
  # before_action :ensure_frame_response, only: [:new, :create, :title]
  before_action :set_recipe, only: %i[ show edit edit_title update_title create_directions update destroy ]


  # GET /recipes or /recipes.json
  def index
    @pagy, @recipes = pagy(Recipe.includes(:recipe_category).order(created_at: :DESC))
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe_ingredients = Ingredient.includes(:grocery, :measurement_unit, :ingredient_state).where(recipe_id: @recipe.id).order("id ASC")
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @recipe_ingredients = Ingredient.includes(:grocery, :measurement_unit, :ingredient_state).where(recipe_id: @recipe.id).order("id ASC")
          
    # Turbo::StreamsChannel.broadcast_append_to :recipe_form_update, 
    #   target: "recipe-ingredients--list", 
    #   partial: "recipes/recipe_sub_ingredient", 
    #   locals: {id: @recipe.id, recipe_ingredient: @recipe_ingredients, recipe: @recipe}
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.turbo_stream
        format.html { redirect_to admins_recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.turbo_stream
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # def create_ingredient
  #   @recipe = Recipe.find(params[:id])
  #   @recipe_ingredient = @recipe.ingredients.new(quantity: recipe_ingredient_params[:quantity], grocery_id: recipe_ingredient_params[:grocery_id], measurement_unit_id: recipe_ingredient_params[:measurement_unit_id], ingredient_state_id: recipe_ingredient_params[:ingredient_state_id])
    
  #   respond_to do |format|
  #     if @recipe_ingredient.save
  #       # Turbo::StreamsChannel.broadcast_prepend_to :recipe_form_update, 
  #         #   target: "recipe_#{@recipe.id}", 
  #         #   partial: "admins/recipes/ingredient/recipe_sub_ingredient_list", 
  #         #   locals: {
  #           #     recipe_id: @recipe.id, 
  #         #     index: 0, 
  #         #     ingredient: @recipe_ingredient, 
  #         #     recipe: @recipe
  #         #   }

          
  #         flash.now[:notice] = "Recipe was successfully updated." 
  #         flash.now[:alert] = "Recipe was successfully updated." 
  #         # render turbo_stream: [
  #         #       turbo_stream.prepend(
  #         #         "recipe_#{@recipe.id}",
  #         #         partial: "admins/recipes/ingredient/recipe_sub_ingredient_list",
  #         #         locals: {
  #         #           recipe_id: @recipe.id, 
  #         #           index: 0, 
  #         #           ingredient: @recipe_ingredient, 
  #         #           recipe: @recipe
  #         #         },
  #         #       ),
  #         #       turbo_stream.replace("flash", partial: "application/flash"),
  #         #     ]

  #       format.turbo_stream
  #       format.html {  }
  #       format.js
  #       format.json { render json: {status: :ok } }    
  #     else  
  #       flash.now[:notice] = @recipe_ingredient.errors
  #       Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, 
  #           target: "recipe_ingredient_form", 
  #           partial: "admins/recipes/ingredient/recipe_sub_ingredient_form", 
  #           locals: {
  #             ingredient: @recipe_ingredient, 
  #             recipe_id: @recipe.id
  #           }


  #       # format.html { render :edit, status: :unprocessable_entity }
  #       # format.json { render json: @recipe_ingredient.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end



  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
   
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to edit_admins_recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to admins_recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # DIRECTIONS -------------------------------------
  
  # DIRECTIONS -------------------------------------

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :image, :recipe_category_id, :status)
    end

    def recipe_ingredient_params
      params.permit(:quantity, :ingredient_state_id, :measurement_unit_id, :grocery_id)
    end

    # def ensure_frame_response
    #   return unless Rails.env.development?
    #   redirect_to recipes_url unless turbo_frame_request?
    # end
end

app/controllers/api/v1/admins/recipe_controller.rb
module Api
  module V1
    module Admins
      class RecipeController < DashboardsController
        before_action :set_recipe, only: %i[  edit_title update_title create_directions ]

        def new_title
          @recipe = Recipe.new
        end

        def create_title
          if params[:edit]
            @recipe = Recipe.find(params[:id])
            @recipe.title = params[:title]
          else
            @recipe = Recipe.new(recipe_params)
          end


          respond_to do |format| 
            if @recipe.save
              # format.turbo_stream {render turbo_stream: turbo_stream.replace(@recipe)}
              # format.turbo_stream
              # format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
              # Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, target: "recipe-update-#{@recipe.id}", partial: "recipes/recipe_sub_form", locals: {id: @recipe.id}
              format.json { render :show, status: :created, location: @recipe }
            else
              format.html { render :new_title, status: :unprocessable_entity }
              format.json { render json: @recipe.errors, status: :unprocessable_entity }
            end
          end
        end

        def edit_title
        end

        def update_title
          respond_to do |format| 
            if @recipe.update(recipe_params)
              # format.turbo_stream {render turbo_stream: turbo_stream.replace(@recipe)}
              # format.turbo_stream
              # format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
              # Turbo::StreamsChannel.broadcast_replace_to :recipe_form_update, target: "recipe-update-#{@recipe.id}", partial: "recipes/recipe_sub_form", locals: {id: @recipe.id}
              format.json { render :index, status: :created, location: @recipe }
            else
              format.html { render :new_title, status: :unprocessable_entity }
              format.json { render json: @recipe.errors, status: :unprocessable_entity }
            end
          end
        end

        def new_ingredient
          @ingredient = Ingredient.new
          @recipe_id = params[:id]
        end

        def edit_ingredient
        end

        def create_directions
          params[:direction].each do |index, item|
            @recipe.directions << item
          end

          if @recipe.save
            Turbo::StreamsChannel.broadcast_prepend_to :recipe_form_update, 
                  target: "recipe_#{@recipe.id}", 
                  partial: "admins/recipes/recipe_sub_ingredient_list", 
                  locals: {id: @recipe.id, index: 0, ingredient: @recipe_ingredient, recipe: @recipe}

            flash.now[:notice] = "Recipe direction created successfully"

            format.turbo_stream
            format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
            format.json { render :show, status: :ok, location: @recipe }
          else 
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end
        end

        def edit_direction
          direction_id = params[:direction_id].to_i
          @direction_id = direction_id || 2
          # @ingredient = Recipe.find(params[:recipe_id]).directions.select.with_index{ |direction, index| index === direction_id}
          ingredient = Recipe.find(params[:recipe_id]).directions
          @ingredient = ingredient.select.with_index{|ingredient, idx|  idx === direction_id}
          @recipe_id = params[:recipe_id]
        end

        def update_direction
          ingredient = Recipe.find(params[:recipe_id])
          ingredient.directions[params[:id].to_i] = params[:direction]

          if  ingredient.save!
            # Turbo::StreamsChannel.broadcast_prepend_to :recipe_form_update, 
            #       target: "recipe_#{@recipe.id}", 
            #       partial: "recipes/recipe_sub_ingredient_list", 
            #       locals: {id: @recipe.id, index: 0, ingredient: @recipe_ingredient, recipe: @recipe}
            flash.now[:notice] = "Recipe direction updated successfully"

            format.turbo_stream

            format.html {  }
            format.json {  }
          else 
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end
        end


        def delete_direction
          ingredient = Recipe.find(params[:recipe_id])
          ingredient.directions.delete_at(params[:id])

          if  ingredient.save!
            Turbo::StreamsChannel.broadcast_remove_to :recipe_form_update, target: "edit_ddirection_#{params[:id]}"

            flash.now[:alert] = "Recipe direction deleted successfully"
            format.html {  }
            format.json {  }
          else 
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @recipe.errors, status: :unprocessable_entity }
          end
        end


        private

        def set_recipe
          @recipe = Recipe.find(params[:id])
        end

      end
    end
  end
end

app/controllers/api/v1/users/plans_controller.rb
module Api
  module V1
    module Users
      class PlansController < ApplicationController

        def meal_update
          @mealplan = MealPlan.where({plan_id: params[:plan_id], meal_type: params[:meal_type], day: params[:day]}).includes(recipe: [:reviews, {image_attachment: :blob}])
          @mealplan = @mealplan[0]

          if !@mealplan.blank?
            @mealplan.day = params[:day]
            @mealplan.recipe_id = params[:recipe_id]
            @mealplan.meal_type = params[:meal_type]
          else
            @mealplan = MealPlan.create!(plan_id: params[:plan_id], meal_type: params[:meal_type], day: params[:day], recipe_id: params[:recipe_id])
          end

          respond_to do |format|
            if @mealplan.save!

              Turbo::StreamsChannel.broadcast_replace_to :mealplans_list, target: "meal_plan_#{@mealplan[:plan_id]}_#{params[:meal_type]}_#{params[:day]}",
                partial: "users/plans/meal_plan",
                locals: {meals: @mealplan.recipe, meal_type: params[:meal_type], day: params[:day], recipe: @mealplan.recipe, plan_id: @mealplan[:plan_id], id: @mealplan.id}

              format.json { render json: {status: :ok} }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @mealplan.errors, status: :unprocessable_entity }
            end
          end
        end


        # rrefactor this method into its proper controller
        def meal_plans_content
          @meal_plans = Recipe.where(status: "published").includes(:favorites, :meal_plans, :reviews, image_attachment: :blob)
          param = {}
          param[:plan_id] = params[:plan_id]
          param[:meal_type] = params[:meal_type]
          param[:day] = params[:day]

          @params = param

          render(partial: "users/plans/meal_plans_content")
        end


      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  include Accessible
  layout "user_auth"

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  def index
  end
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/recipes_helper.rb
module Users::RecipesHelper
    def average_stars(recipe)
        if recipe.average_stars.zero?
            content_tag(:strong, "No reviews")
        else
            pluralize(number_with_precision(recipe.average_stars, precision: 1), "star")
        end
    end
end

app/views/users/recipes/_favorite_empty.html.erb
<%= turbo_frame_tag "favorite_button" do %>
  <%= button_to recipe_favorites_path(recipe), method: :post, class: "flex text-red-600 items-center" do %>
    <i class="bi bi-heart"></i>
  <% end %>
<% end %>

app/views/users/recipes/_images.html.erb
<%= turbo_frame_tag id="image-1" %>
Loaded
<% end %>

app/views/users/recipes/_recipe_plan_sub_ingredient.html.erb
<ul id="recipe_<%= recipe.id %>" class="flex flex-col">
  <% count = 0 %>
  <% recipe_ingredient.each do |index, ingredient| %>
    <% unless ingredient.nil? %>
      <li id="ingredient--#<%= ingredient[:id] %>" class="flex justify-between bg-gray-50 hover:bg-gray-200 gap-2 mb-1">
        <div class="flex gap-2">
          <span class="w-8 text-white font-extrabold px-3 bg-gray-200">
            <%= count += 1  %>
          </span>
          <span>
            <%= render "users/recipes/ingredient_quantity", quantity: ingredient[:quantity], id: ingredient[:id] %>
            - <%= ingredient[:grocery] %> - <%= ingredient[:ingredient_state] %>
            <%= ingredient[:measurement_unit] %>
          </span>
        </div>
        <% if admin_signed_in? %>
          <span class="flex items-center gap-1 py-1">
            <%= button_to  ingredient_path(ingredient[:id]), 
        method: :get, 
        data: {turbo_frame: 'modal'}, class: "bg-gray-500 hover:bg-gray-700 text-gray-200 hover:text-white px-1 rounded-md" do %>
              <i class="bi bi-eye"></i>
            <% end %>
            <%= button_to  edit_ingredient_path(ingredient[:id]), 
        method: :get, 
        params: {recipe_id: ingredient.recipe_id}, 
        data: {turbo_frame: 'modal'}, class: "bg-gray-300 hover:bg-gray-700 text-black hover:text-white px-1 rounded-md" do %>
              <i class="bi bi-pencil"></i>
            <% end %>
            <%= link_to ingredient_path(ingredient[:id]), 
          data: { 'turbo-method': "delete", 'delete-target': "link", 
          action: "turbo:click->recipe#delete" },  
          class: "bg-gray-300 hover:bg-red-700 text-red-400 text-black hover:text-white px-1 rounded-md" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </span>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/recipes/_recipe_sub_ingredient.html.erb
<ul id="recipe_<%= recipe.id %>" class="flex flex-col">
  <% count = 0 %>
  <% recipe_ingredient.each do |index, ingredient| %>
    <% unless ingredient.nil? %>
      <li id="ingredient--#<%= ingredient[:id] %>" class="flex justify-between bg-gray-50 hover:bg-gray-200 gap-2 mb-1">
        <div class="flex gap-2">
          <span class="w-8 text-white font-extrabold px-3 bg-gray-200">
            <%= count += 1  %>
          </span>
          <span>
            <%= render "users/recipes/ingredient_quantity", quantity: ingredient[:quantity], id: ingredient[:id] %>
            - <%= ingredient[:grocery] %> - <%= ingredient[:ingredient_state] %>
            <%= ingredient[:measurement_unit] %>
          </span>
        </div>
        <% if admin_signed_in? %>
          <span class="flex items-center gap-1 py-1">
            <%= button_to  ingredient_path(ingredient[:id]), 
        method: :get, 
        data: {turbo_frame: 'modal'}, class: "bg-gray-500 hover:bg-gray-700 text-gray-200 hover:text-white px-1 rounded-md" do %>
              <i class="bi bi-eye"></i>
            <% end %>
            <%= button_to  edit_ingredient_path(ingredient[:id]), 
        method: :get, 
        params: {recipe_id: ingredient.recipe_id}, 
        data: {turbo_frame: 'modal'}, class: "bg-gray-300 hover:bg-gray-700 text-black hover:text-white px-1 rounded-md" do %>
              <i class="bi bi-pencil"></i>
            <% end %>
            <%= link_to ingredient_path(ingredient[:id]), 
          data: { 'turbo-method': "delete", 'delete-target': "link", 
          action: "turbo:click->recipe#delete" },  
          class: "bg-gray-300 hover:bg-red-700 text-red-400 text-black hover:text-white px-1 rounded-md" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </span>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/recipes/show.html.erb
<div class="page-container">
  <div class="grid mb-16">
    <h1 class="flex flex-col sm:flex-row sm:justify-between p-4  bg-accent/20">
      <span class="text-gray-700 text-3xl"><%= @recipe.title %></span>
    </h1>
    <div class="w-full my-4">
      <% if @recipe.image.attached? %>
        <%= image_tag @recipe&.image.variant(resize_to_fill: [1000, 400], format: :jpg, saver: { strip: true, quality: 50 } ), class: "w-full object-cover" %>
      <% else %>
        <span class="text-red-700"> No image attached yet!!!</span>
      <% end %>
    </div>
    <%= turbo_stream_from :servings %>
    <div class="w-full py-2 my-4 flex justify-between">
      <span><% mealplan =  @recipe.meal_plans.find(params[:meal_plan_id].to_i) %></span>
      <div class="flex gap-4">
        <div class="flex items-center gap-2">
          <%= button_to delete_serving_meal_plan_path(params[:meal_plan_id]), 
              params: {plan_id: mealplan[:plan_id], day: mealplan[:day], meal_type: mealplan[:meal_type]}, 
              method: :delete, 
              class: "bg-gray-200 text-gray-600 px-2 text-2xl rounded-md" do %>
            <i class="bi bi-dash"></i>
          <% end %>
          <%= render "serving", serving: mealplan.number_of_persons_to_be_served %>
          <%= button_to create_serving_meal_plan_path(params[:meal_plan_id]), 
              params: {plan_id: mealplan[:plan_id], day: mealplan[:day], meal_type: mealplan[:meal_type]}, 
              method: :patch, 
              class: "bg-gray-200 text-gray-600 px-2 text-2xl rounded-md" do %>
            <i class="bi bi-plus"></i>
          <% end %>
        </div>
        <span class="flex items-center border-x border-gray-500 px-2">
          <i class="bi bi-printer"></i>
        </span>
        <!----------------------------------------------->
        <div class="flex items-center">
          <%= turbo_stream_from "favorite" %>
          <%#= turbo_frame_tag "favorite_button" %>
          <% if @favorite.present? %>
            <%= render "favorite_fill", recipe: @recipe %>
          <% else %>
            <%= render "favorite_empty", recipe: @recipe %>
          <% end %>
        </div>
      </div>
    </div>
    <div  data-value-id="<%= @recipe.id %>"  class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4" id="recipe-update-33">
      <!----- Ingredients  ------>
      <%= render 'users/recipes/recipe_plan_sub_ingredient', recipe_ingredient: @recipe_ingredients, recipe: @recipe %>
      <!----- Instructions ------>
      <%= render "admins/recipes/direction/recipe_sub_direction", id: @recipe[:id], directions: @recipe[:directions] %>
    </div>
  </div>
  <!-- ----------------------------------------- -->
  <!-- ------------- START REVIEWS ------------- -->
  <%= render "users/recipes/single_recipe_reviews", review: @recipe.reviews, recipe: @recipe  %>
  <!-- ------------- END REVIEWS ------------- -->
  <!-- --------------------------------------- -->
  <div class="flex justify-end gap-4 p-4 bg-gray-700 text-gray-200">
    <% if admin_signed_in? %>
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
    <% end %>
    <%= link_to "Back to recipes", recipes_path %>
    <%#= button_to "Destroy this recipe", @recipe, method: :delete %>
  </div>
</div>

app/views/users/recipes/single_post.html.erb
 <%= turbo_frame_tag id: "single_recipe_#{@recipe.id}" do %>
  <h1 class="flex flex-col sm:flex-row sm:justify-between p-4  border-l-8 border-accent/20">
    <span class="text-gray-700 text-3xl"><%= @recipe.title %></span>
  </h1>
  <div class="w-full my-4">
    <% if @recipe.image.attached? %>
      <%= image_tag @recipe&.image.variant(resize_to_fill: [1000, 300]), class: "w-full object-cover" %>
    <% else %>
      <span class="text-red-700"> No image attached yet!!!</span>
    <% end %>
  </div>
  <!-- -------------------------------------------- -->
  <%= turbo_stream_from :servings %>
  <div class="w-full py-2 my-4 flex justify-end">
    <div class="flex gap-4">
      <div class="w-full flex items-center gap-2 bg-gray-400">
        <span class="flex items-center border-x border-gray-500 px-2">
          <i class="bi bi-printer"></i>
        </span>
        <!----------------------------------------------->
        <div class="flex items-center">
          <%= turbo_stream_from "favorite" %>
          <% if @recipe.favorites[0].present? %>
            <%= render "favorite_fill", recipe: @recipe %>
          <% else %>
            <%= render "favorite_empty", recipe: @recipe %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- -------------------------------------------- -->
    <%= debug @recipe.ingredients %>
    <% unless @recipe.ingredients.empty? %>
      <div  data-value-id="<%= @recipe.id %>"  class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4" id="recipe-update-33">
        <!----- Ingredients  ------>
        <%= render 'users/recipes/recipe_sub_ingredient', recipe_ingredient: @recipe.ingredients, recipe: @recipe %>
        <!----- Instructions ------>
        <%#= debug @recipe.ingredients %>
      </div>
    <% end %>
  </div>
  <!-- -------------------------------------------- -->
  <div class="sm:flex shadow-md my-8 p-4">
    <div>
      <div>
        <h3 class="text-2xl text-gray-500">Reviews</h3>
        <div class="flex gap-4">
          <%= button_to "Write Review", recipe_review_path(@recipe), 
          params: {recipe_id: @recipe.id}, 
          method: :post,
          data: { turbo_frame: "write-review" }, 
          class: "button button--secondary" 
        %>
          <%= link_to pluralize(@recipe.reviews.size, "Review"), recipe_reviews_path(@recipe) %>
        </div>
      </div>
      <%= turbo_frame_tag "write-review"  %>
      <%# --------------------------------- %>
      <ul class="flex flex-col gap-4 reviews">
        <%= debug @recipe.reviews %>
        <%= turbo_stream_from "review-list" %>
        <% @recipe.reviews.each do |review| %>
          <% unless review.parent_id || !review.persisted? %>
            <li class="bg-gray-50 my-1 p-4" id="review-<%= review.id %>">
              <%= render "shared/stars", recipe: @recipe, review: review  %>
              <p>
                <%= review.user.name if review.user.name.present? %>
                <span class="text-xs text-gray-500 italic">
                  <%= time_ago_in_words(review.created_at) %> ago
                </span>
              </p>
              <p>
                <%= review.comment %>
              </p>
              <%= render 'users/reviews/review', review: review.replies, recipe: @recipe if review.replies.any? %>
              <% unless current_user.nil? %>
                <%= button_to 'Reply', reply_recipe_reviews_path(@recipe), 
                  params: {parent_id: review.id},
                  method: :post,
                  data: { turbo_frame: "review-#{review.id}"}, 
                  class: "bg-primary px-2 py-1 rounded-sm text-xs"
                %>
              <% end %>
              <%= turbo_frame_tag "review-#{review.id}" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <%# --------------------------------- %>
    </div>
  </div>
<% end %>